// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"
	"log"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (
        email,
        phone_number,
        password_hash
    )
VALUES ($1, $2, $3)
RETURNING
    id,
    email,
    phone_number,
    role,
    deleted,
    created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PhoneNumber  string `json:"phone_number"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	PhoneNumber string             `json:"phone_number"`
	Role        UserRole           `json:"role"`
	Deleted     bool               `json:"deleted"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Active: 1760184803924@@127.0.0.1@5432
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PhoneNumber, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.Role,
		&i.Deleted,
		&i.CreatedAt,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT
    id,
    email,
    phone_number,
    role,
    deleted,
    created_at,
    updated_at
FROM users
WHERE
    deleted = FALSE
ORDER BY created_at DESC
LIMIT $1
OFFSET
    $2
`

type GetAllUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllUsersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	PhoneNumber string             `json:"phone_number"`
	Role        UserRole           `json:"role"`
	Deleted     bool               `json:"deleted"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]GetAllUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PhoneNumber,
			&i.Role,
			&i.Deleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    email,
    phone_number,
    role,
    deleted,
    created_at,
    updated_at
FROM users
WHERE
    email = $1
    
`

type GetUserByEmailRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	PhoneNumber string             `json:"phone_number"`
	Role        UserRole           `json:"role"`
	Deleted     bool               `json:"deleted"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	log.Println(email)
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.Role,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
